"""add diagram collaborators

Revision ID: 3f9f653ec7cc
Revises: cd269a313b01
Create Date: 2026-09-15 16:37:00.794613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9f653ec7cc'
down_revision: Union[str, Sequence[str], None] = 'cd269a313b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_collaborator',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagram_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('EDITOR', 'VIEWER', name='collaborator_role'), server_default='EDITOR', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagram.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagram_id', 'user_id', name='uq_diagram_collaborator_diagram_user')
    )
    op.create_index(op.f('ix_diagram_collaborator_diagram_id'), 'diagram_collaborator', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_diagram_collaborator_user_id'), 'diagram_collaborator', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagram_collaborator_user_id'), table_name='diagram_collaborator')
    op.drop_index(op.f('ix_diagram_collaborator_diagram_id'), table_name='diagram_collaborator')
    op.drop_table('diagram_collaborator')
    # ### end Alembic commands ###
