"""init schema

Revision ID: a112c4d14f5b
Revises: 
Create Date: 2025-10-21 21:02:31.763531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a112c4d14f5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='user_role'), server_default=sa.text("'editor'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('diagram',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clase',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('diagram_id', sa.UUID(), nullable=False),
    sa.Column('x_grid', sa.Integer(), server_default='0', nullable=False),
    sa.Column('y_grid', sa.Integer(), server_default='0', nullable=False),
    sa.Column('w_grid', sa.Integer(), server_default='12', nullable=False),
    sa.Column('h_grid', sa.Integer(), server_default='6', nullable=False),
    sa.Column('z_index', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagram.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clase_diagram_id'), 'clase', ['diagram_id'], unique=False)
    op.create_table('atributo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('requerido', sa.Boolean(), nullable=False),
    sa.Column('clase_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo_retorno', sa.String(length=60), nullable=False),
    sa.Column('clase_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagram_id', sa.UUID(), nullable=False),
    sa.Column('origen_id', sa.UUID(), nullable=False),
    sa.Column('destino_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('ASSOCIATION', 'AGGREGATION', 'COMPOSITION', 'INHERITANCE', 'DEPENDENCY', name='reltype'), nullable=False),
    sa.Column('etiqueta', sa.String(length=200), nullable=True),
    sa.Column('src_anchor', sa.String(length=8), server_default='right', nullable=False),
    sa.Column('dst_anchor', sa.String(length=8), server_default='left', nullable=False),
    sa.Column('src_offset', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dst_offset', sa.Integer(), server_default='0', nullable=False),
    sa.Column('src_lane', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dst_lane', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mult_origen_min', sa.Integer(), server_default='1', nullable=False),
    sa.Column('mult_origen_max', sa.Integer(), nullable=True),
    sa.Column('mult_destino_min', sa.Integer(), server_default='1', nullable=False),
    sa.Column('mult_destino_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destino_id'], ['clase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagram.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origen_id'], ['clase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relacion_diagram_id'), 'relacion', ['diagram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relacion_diagram_id'), table_name='relacion')
    op.drop_table('relacion')
    op.drop_table('metodo')
    op.drop_table('atributo')
    op.drop_index(op.f('ix_clase_diagram_id'), table_name='clase')
    op.drop_table('clase')
    op.drop_table('diagram')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
