"""add unique constraint on attribute and method names per class

Revision ID: cd269a313b01
Revises: a112c4d14f5b
Create Date: 2026-09-15 10:29:56.268560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd269a313b01'
down_revision: Union[str, Sequence[str], None] = 'a112c4d14f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_atributo_clase_nombre', 'atributo', ['clase_id', 'nombre'])
    op.create_unique_constraint('uq_metodo_clase_nombre', 'metodo', ['clase_id', 'nombre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_metodo_clase_nombre', 'metodo', type_='unique')
    op.drop_constraint('uq_atributo_clase_nombre', 'atributo', type_='unique')
    # ### end Alembic commands ###
